backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"
publish_mode: editorial_workflow

collections:
  - name: blog
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    media_folder: ''
    public_folder: './'
    fields: 
      - {label: "Title", name: title, widget: string}
      - {label: "Description", name: description, widget: string}
      - {label: "PublishDate", name: pubDate, widget: datetime}
      - {label: "Updated At", name: updatedDate, widget: datetime}
      - label: "Hero Images"
        name: "heroImage"
        widget: "list"
        summary: '{{fields.image}}'
        field: {label: Image, name: image, widget: image}
      - {label: "Tags", name: "tags", widget: list}
      - {label: Body, name: body, widget: markdown}
